default: sfml
    
sfml:
	g++ -O3 ant.cpp color.cpp main.cpp -std=c++17 -I/opt/homebrew/include/ -o fractalDraw -L/opt/homebrew/lib -lsfml-graphics -lsfml-window -lsfml-system -L/Users/johnwhitman/Projects/vivid -lvivid